"""
Shared constants package.
"""
from .sync_constants import (
    # Branch defaults
    DEFAULT_BRANCH,
    DEFAULT_BRANCH_FALLBACKS,

    # Batch processing
    GITLAB_SYNC_BATCH_SIZE_DEFAULT,
    GITLAB_SYNC_BATCH_SIZE_MIN,
    GITLAB_SYNC_BATCH_SIZE_MAX,
    SYNC_QUEUE_BULK_INSERT_BATCH_SIZE,

    # Priorities
    SYNC_PRIORITY_CODE,
    SYNC_PRIORITY_DOCS,
    SYNC_PRIORITY_CONFIG,
    SYNC_PRIORITY_OTHER,

    # Code chunking
    CODE_CHUNK_MAX_FILE_SIZE,
    CODE_CHUNK_SIZE,
    CODE_CHUNK_OVERLAP,
    CODE_CHUNK_MAX_LINES_PER_CHUNK,
    CODE_CHUNK_CONFIG_BY_LANGUAGE,

    # Exclude patterns
    CODE_EXCLUDE_PATTERNS,
    SUPPORTED_CODE_EXTENSIONS,

    # GitLab API
    GITLAB_API_MAX_PER_PAGE,
    GITLAB_API_DEFAULT_PER_PAGE,
)

__all__ = [
    # Branch
    "DEFAULT_BRANCH",
    "DEFAULT_BRANCH_FALLBACKS",

    # Batch
    "GITLAB_SYNC_BATCH_SIZE_DEFAULT",
    "GITLAB_SYNC_BATCH_SIZE_MIN",
    "GITLAB_SYNC_BATCH_SIZE_MAX",
    "SYNC_QUEUE_BULK_INSERT_BATCH_SIZE",

    # Priority
    "SYNC_PRIORITY_CODE",
    "SYNC_PRIORITY_DOCS",
    "SYNC_PRIORITY_CONFIG",
    "SYNC_PRIORITY_OTHER",

    # Chunking
    "CODE_CHUNK_MAX_FILE_SIZE",
    "CODE_CHUNK_SIZE",
    "CODE_CHUNK_OVERLAP",
    "CODE_CHUNK_MAX_LINES_PER_CHUNK",
    "CODE_CHUNK_CONFIG_BY_LANGUAGE",

    # Patterns
    "CODE_EXCLUDE_PATTERNS",
    "SUPPORTED_CODE_EXTENSIONS",

    # API
    "GITLAB_API_MAX_PER_PAGE",
    "GITLAB_API_DEFAULT_PER_PAGE",
]
