"""initial_schema

Revision ID: b06a66f9583a
Revises:
Create Date: 2025-11-14 03:28:12.451331+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b06a66f9583a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Model name (e.g., gpt-4o, claude-3-5-sonnet)",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_models_id"), "ai_models", ["id"], unique=False)
    op.create_index(op.f("ix_ai_models_name"), "ai_models", ["name"], unique=True)
    op.create_table(
        "connectors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Connector name (e.g., GitLab, GitHub)",
        ),
        sa.Column(
            "provider_type",
            sa.String(length=50),
            nullable=False,
            comment="Provider type (gitlab, github, jira, etc.)",
        ),
        sa.Column(
            "auth_type",
            sa.String(length=20),
            nullable=False,
            comment="Authentication type (oauth2, personal_token, api_key)",
        ),
        sa.Column("client_id", sa.Text(), nullable=True, comment="OAuth2 client ID (encrypted)"),
        sa.Column(
            "client_secret", sa.Text(), nullable=True, comment="OAuth2 client secret (encrypted)"
        ),
        sa.Column(
            "config_schema",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Configuration schema for this connector",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=True, comment="Whether this connector is active"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider_type"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("s3_key", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("upload_status", sa.String(), nullable=False),
        sa.Column("processing_status", sa.String(), nullable=True),
        sa.Column("knowledge_base_id", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=True),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.create_index(op.f("ix_groups_name"), "groups", ["name"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "chatbots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "model_id", sa.Integer(), nullable=False, comment="Foreign key to ai_models table"
        ),
        sa.Column(
            "temperature",
            sa.Numeric(precision=3, scale=2),
            nullable=True,
            comment="0.0-2.0, controls randomness",
        ),
        sa.Column("max_tokens", sa.Integer(), nullable=True, comment="Maximum response length"),
        sa.Column(
            "top_p",
            sa.Numeric(precision=3, scale=2),
            nullable=True,
            comment="0.0-1.0, nucleus sampling",
        ),
        sa.Column(
            "system_prompt",
            sa.Text(),
            nullable=True,
            comment="Instructions defining bot personality and behavior",
        ),
        sa.Column(
            "welcome_message", sa.Text(), nullable=True, comment="First message sent to users"
        ),
        sa.Column("fallback_message", sa.Text(), nullable=True, comment="Response when API fails"),
        sa.Column(
            "max_conversation_length",
            sa.Integer(),
            nullable=True,
            comment="Messages to remember in context",
        ),
        sa.Column(
            "enable_function_calling",
            sa.Boolean(),
            nullable=True,
            comment="Allow AI to use available tools",
        ),
        sa.Column(
            "created_by", sa.Integer(), nullable=False, comment="Admin who created this chatbot"
        ),
        sa.Column(
            "status", sa.String(length=20), nullable=True, comment="active, disabled, archived"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_id"], ["ai_models.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_connections",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="User who owns this connection"),
        sa.Column("connector_id", sa.Integer(), nullable=False, comment="Connector being used"),
        sa.Column("access_token", sa.Text(), nullable=True, comment="Access token (encrypted)"),
        sa.Column(
            "refresh_token",
            sa.Text(),
            nullable=True,
            comment="Refresh token (encrypted) for OAuth2",
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=True, comment="Token expiration timestamp"),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional metadata (project_id, repository_id, etc.) - NO SENSITIVE DATA",
        ),
        sa.Column(
            "is_active", sa.Boolean(), nullable=True, comment="Whether this connection is active"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["connector_id"], ["connectors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("added_by", sa.Integer(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["added_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    op.create_table(
        "chatbot_tools",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chatbot_id", sa.Integer(), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("tool_config", sa.Text(), nullable=True, comment="JSON tool configuration"),
        sa.Column("is_enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["chatbot_id"], ["chatbots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chatbot_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("last_message_at", sa.DateTime(), nullable=True),
        sa.Column("last_accessed_at", sa.DateTime(), nullable=True),
        sa.Column("message_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["chatbot_id"], ["chatbots.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_chatbots",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("chatbot_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_by",
            sa.Integer(),
            nullable=False,
            comment="Admin who assigned this chatbot to the group",
        ),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True, comment="active, revoked"),
        sa.ForeignKeyConstraint(["assigned_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["chatbot_id"], ["chatbots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "chatbot_id"),
    )
    op.create_table(
        "knowledge_bases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chatbot_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "vector_store_type", sa.String(length=50), server_default="chromadb", nullable=False
        ),
        sa.Column("vector_store_collection", sa.String(length=255), nullable=True),
        sa.Column("vector_store_config", sa.JSON(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["chatbot_id"], ["chatbots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_bases_chatbot_id"), "knowledge_bases", ["chatbot_id"], unique=False
    )
    op.create_table(
        "repositories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "connection_id",
            sa.Integer(),
            nullable=False,
            comment="User connection that owns this repository",
        ),
        sa.Column(
            "external_id", sa.Text(), nullable=False, comment="Repository ID on external platform"
        ),
        sa.Column("name", sa.String(length=255), nullable=False, comment="Repository name"),
        sa.Column("full_name", sa.Text(), nullable=True, comment="Full repository path"),
        sa.Column(
            "visibility", sa.String(length=20), nullable=True, comment="Repository visibility"
        ),
        sa.Column("html_url", sa.Text(), nullable=True, comment="Web URL to repository"),
        sa.Column(
            "default_branch", sa.String(length=100), nullable=True, comment="Default branch name"
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional metadata",
        ),
        sa.Column(
            "last_synced_at",
            sa.DateTime(),
            nullable=True,
            comment="Last time this repository was synced",
        ),
        sa.Column(
            "sync_status",
            sa.String(length=20),
            nullable=True,
            comment="Sync status (pending, syncing, completed, failed)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True,
            comment="Whether this repository is actively synced",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["connection_id"], ["user_connections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_chatbots",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chatbot_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_by",
            sa.Integer(),
            nullable=False,
            comment="Admin who assigned this chatbot to the user",
        ),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True, comment="active, revoked"),
        sa.ForeignKeyConstraint(["assigned_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["chatbot_id"], ["chatbots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "chatbot_id"),
    )
    op.create_table(
        "commits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "repo_id", sa.Integer(), nullable=False, comment="Repository this commit belongs to"
        ),
        sa.Column(
            "external_id", sa.Text(), nullable=False, comment="Commit ID on external platform"
        ),
        sa.Column("sha", sa.String(length=40), nullable=False, comment="Git commit SHA"),
        sa.Column(
            "author_name", sa.String(length=255), nullable=True, comment="Commit author name"
        ),
        sa.Column(
            "author_email", sa.String(length=255), nullable=True, comment="Commit author email"
        ),
        sa.Column("message", sa.Text(), nullable=True, comment="Commit message"),
        sa.Column("committed_at", sa.DateTime(), nullable=True, comment="When the commit was made"),
        sa.Column("files_changed", sa.Integer(), nullable=True, comment="Number of files changed"),
        sa.Column("additions", sa.Integer(), nullable=True, comment="Lines added"),
        sa.Column("deletions", sa.Integer(), nullable=True, comment="Lines deleted"),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional commit metadata",
        ),
        sa.Column(
            "synced_at", sa.DateTime(), nullable=True, comment="When this commit was synced to KB"
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_base_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("knowledge_base_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("source_id", sa.String(length=255), nullable=False),
        sa.Column("config", sa.JSON(), nullable=True),
        sa.Column("auto_sync", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("sync_status", sa.String(length=50), nullable=True),
        sa.Column("last_synced_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["knowledge_base_id"], ["knowledge_bases.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_knowledge_base_sources_knowledge_base_id"),
        "knowledge_base_sources",
        ["knowledge_base_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_base_sources_source_id"),
        "knowledge_base_sources",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_knowledge_base_sources_source_type"),
        "knowledge_base_sources",
        ["source_type"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("conversation_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_messages_conversation_id", "messages", ["conversation_id"], unique=False)
    op.create_table(
        "sync_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False, comment="Repository being synced"),
        sa.Column(
            "sync_type", sa.String(length=20), nullable=False, comment="Type: full, incremental"
        ),
        sa.Column(
            "triggered_by",
            sa.String(length=20),
            nullable=True,
            comment="Trigger: manual, scheduled",
        ),
        sa.Column("user_id", sa.Integer(), nullable=True, comment="User who triggered sync"),
        sa.Column(
            "from_commit_sha", sa.String(length=40), nullable=True, comment="Starting commit SHA"
        ),
        sa.Column(
            "to_commit_sha", sa.String(length=40), nullable=False, comment="Ending commit SHA"
        ),
        sa.Column("files_queued", sa.Integer(), nullable=True),
        sa.Column("files_processed", sa.Integer(), nullable=True),
        sa.Column("files_succeeded", sa.Integer(), nullable=True),
        sa.Column("files_failed", sa.Integer(), nullable=True),
        sa.Column("files_skipped", sa.Integer(), nullable=True),
        sa.Column("embeddings_created", sa.Integer(), nullable=True),
        sa.Column("embeddings_deleted", sa.Integer(), nullable=True),
        sa.Column("batches_total", sa.Integer(), nullable=True),
        sa.Column("batches_completed", sa.Integer(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column(
            "parent_sync_id", sa.Integer(), nullable=True, comment="Parent sync if this is a retry"
        ),
        sa.Column("api_calls_made", sa.Integer(), nullable=True),
        sa.Column("avg_file_process_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Status: running, completed, failed, partial, retrying",
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Sanitized error message"),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["parent_sync_id"], ["sync_history.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "file_change_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "repo_id", sa.Integer(), nullable=False, comment="Repository this change belongs to"
        ),
        sa.Column(
            "commit_id", sa.Integer(), nullable=True, comment="Commit that changed this file"
        ),
        sa.Column(
            "sync_history_id",
            sa.Integer(),
            nullable=True,
            comment="Sync session that processed this change",
        ),
        sa.Column("file_path", sa.Text(), nullable=False, comment="Path to file in repository"),
        sa.Column(
            "change_type",
            sa.String(length=20),
            nullable=False,
            comment="Type: added, modified, deleted, renamed",
        ),
        sa.Column("old_path", sa.Text(), nullable=True, comment="Previous path for renamed files"),
        sa.Column("additions", sa.Integer(), nullable=True, comment="Lines added"),
        sa.Column("deletions", sa.Integer(), nullable=True, comment="Lines deleted"),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=True, comment="When embedding was created"),
        sa.Column(
            "sync_status",
            sa.String(length=20),
            nullable=True,
            comment="Status: pending, synced, failed, skipped",
        ),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("last_retry_at", sa.DateTime(), nullable=True),
        sa.Column(
            "next_retry_at",
            sa.DateTime(),
            nullable=True,
            comment="When to retry (exponential backoff)",
        ),
        sa.Column(
            "error_type",
            sa.String(length=50),
            nullable=True,
            comment="Error category: api_error, parse_error, timeout, etc.",
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="Sanitized error message"),
        sa.Column(
            "process_time_ms",
            sa.Integer(),
            nullable=True,
            comment="Time taken to process this file",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["commit_id"], ["commits.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["sync_history_id"], ["sync_history.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sync_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False, comment="Repository"),
        sa.Column(
            "commit_id", sa.Integer(), nullable=False, comment="Commit that changed this file"
        ),
        sa.Column(
            "file_change_history_id",
            sa.Integer(),
            nullable=True,
            comment="Reference to file change history",
        ),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("change_type", sa.String(length=20), nullable=False),
        sa.Column(
            "priority", sa.Integer(), nullable=True, comment="Higher priority processed first"
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=True,
            comment="Status: pending, processing, completed, failed",
        ),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True, comment="Last error message (sanitized)"),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "next_retry_at",
            sa.DateTime(),
            nullable=True,
            comment="When to retry with exponential backoff",
        ),
        sa.ForeignKeyConstraint(["commit_id"], ["commits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["file_change_history_id"], ["file_change_history.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["repo_id"], ["repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_queue")
    op.drop_table("file_change_history")
    op.drop_table("sync_history")
    op.drop_index("idx_messages_conversation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_index(
        op.f("ix_knowledge_base_sources_source_type"), table_name="knowledge_base_sources"
    )
    op.drop_index(op.f("ix_knowledge_base_sources_source_id"), table_name="knowledge_base_sources")
    op.drop_index(
        op.f("ix_knowledge_base_sources_knowledge_base_id"), table_name="knowledge_base_sources"
    )
    op.drop_table("knowledge_base_sources")
    op.drop_table("commits")
    op.drop_table("user_chatbots")
    op.drop_table("repositories")
    op.drop_index(op.f("ix_knowledge_bases_chatbot_id"), table_name="knowledge_bases")
    op.drop_table("knowledge_bases")
    op.drop_table("group_chatbots")
    op.drop_table("conversations")
    op.drop_table("chatbot_tools")
    op.drop_table("user_groups")
    op.drop_table("user_connections")
    op.drop_table("chatbots")
    op.drop_table("users")
    op.drop_index(op.f("ix_groups_name"), table_name="groups")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_table("groups")
    op.drop_table("documents")
    op.drop_table("connectors")
    op.drop_index(op.f("ix_ai_models_name"), table_name="ai_models")
    op.drop_index(op.f("ix_ai_models_id"), table_name="ai_models")
    op.drop_table("ai_models")
    # ### end Alembic commands ###
