CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "is_admin" boolean DEFAULT false,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "status" varchar(20) DEFAULT 'active',
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "user_groups" (
  "user_id" integer NOT NULL,
  "group_id" integer NOT NULL,
  "added_by" integer NOT NULL,
  "joined_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("user_id", "group_id")
);

CREATE TABLE "groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "chatbots" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "description" text,
  "provider" varchar(50) NOT NULL,
  "model" varchar(100) NOT NULL,
  "temperature" decimal(3,2) DEFAULT 0.7,
  "max_tokens" integer DEFAULT 2048,
  "top_p" decimal(3,2) DEFAULT 1,
  "system_prompt" text,
  "welcome_message" text,
  "fallback_message" text,
  "max_conversation_length" integer DEFAULT 50,
  "enable_function_calling" boolean DEFAULT true,
  "api_key_encrypted" text NOT NULL,
  "api_base_url" varchar(500),
  "created_by" integer NOT NULL,
  "status" varchar(20) DEFAULT 'active',
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "group_chatbots" (
  "group_id" integer NOT NULL,
  "chatbot_id" integer NOT NULL,
  "assigned_by" integer NOT NULL,
  "assigned_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "status" varchar(20) DEFAULT 'active',
  PRIMARY KEY ("group_id", "chatbot_id")
);

CREATE TABLE "user_chatbots" (
  "user_id" integer NOT NULL,
  "chatbot_id" integer NOT NULL,
  "assigned_by" integer NOT NULL,
  "assigned_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "status" varchar(20) DEFAULT 'active',
  PRIMARY KEY ("user_id", "chatbot_id")
);

CREATE TABLE "tools" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "description" text,
  "status" varchar(20) DEFAULT 'active'
);

CREATE TABLE "chatbot_tools" (
  "chatbot_id" integer NOT NULL,
  "tool_id" integer NOT NULL,
  "added_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  PRIMARY KEY ("chatbot_id", "tool_id")
);

CREATE TABLE "conversations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "chatbot_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "title" varchar(255),
  "status" varchar(20) DEFAULT 'active',
  "is_active" boolean DEFAULT true,
  "started_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "last_message_at" datetime,
  "last_accessed_at" datetime DEFAULT (CURRENT_TIMESTAMP),
  "message_count" integer DEFAULT 0
);

CREATE TABLE "messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversation_id" integer NOT NULL,
  "role" varchar(20) NOT NULL,
  "content" text NOT NULL,
  "metadata" json,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "message_feedback" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "is_positive" boolean NOT NULL,
  "is_reviewed" boolean DEFAULT false,
  "note" text,
  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE INDEX ON "messages" ("conversation_id");

COMMENT ON COLUMN "users"."is_admin" IS 'Admin can create users, chatbots, and groups';

COMMENT ON COLUMN "users"."password_hash" IS 'Encrypted password (bcrypt)';

COMMENT ON COLUMN "users"."status" IS 'active, disabled, suspended';

COMMENT ON COLUMN "user_groups"."added_by" IS 'Admin who added this user to the group';

COMMENT ON COLUMN "chatbots"."provider" IS 'openai, anthropic, google';

COMMENT ON COLUMN "chatbots"."model" IS 'gpt-4o, claude-3-5-sonnet, gemini-pro';

COMMENT ON COLUMN "chatbots"."temperature" IS '0.0-2.0, controls randomness';

COMMENT ON COLUMN "chatbots"."max_tokens" IS 'Maximum response length';

COMMENT ON COLUMN "chatbots"."top_p" IS '0.0-1.0, nucleus sampling';

COMMENT ON COLUMN "chatbots"."system_prompt" IS 'Instructions defining bot personality and behavior';

COMMENT ON COLUMN "chatbots"."welcome_message" IS 'First message sent to users';

COMMENT ON COLUMN "chatbots"."fallback_message" IS 'Response when API fails';

COMMENT ON COLUMN "chatbots"."max_conversation_length" IS 'Messages to remember in context';

COMMENT ON COLUMN "chatbots"."enable_function_calling" IS 'Allow AI to use available tools';

COMMENT ON COLUMN "chatbots"."api_key_encrypted" IS 'Encrypted API credentials';

COMMENT ON COLUMN "chatbots"."api_base_url" IS 'Custom API endpoint for Azure/custom deployments';

COMMENT ON COLUMN "chatbots"."created_by" IS 'Admin who created this chatbot';

COMMENT ON COLUMN "chatbots"."status" IS 'active, disabled, archived';

COMMENT ON COLUMN "group_chatbots"."assigned_by" IS 'Admin who assigned this chatbot to the group';

COMMENT ON COLUMN "group_chatbots"."status" IS 'active, revoked';

COMMENT ON COLUMN "user_chatbots"."assigned_by" IS 'Admin who assigned this chatbot to the user';

COMMENT ON COLUMN "user_chatbots"."status" IS 'active, revoked';

COMMENT ON COLUMN "tools"."name" IS 'Hard-coded tool identifier';

COMMENT ON COLUMN "tools"."description" IS 'Description of what this tool does';

COMMENT ON COLUMN "tools"."status" IS 'active, disabled';

COMMENT ON COLUMN "conversations"."title" IS 'Conversation title, auto-generated or user-defined';

COMMENT ON COLUMN "conversations"."status" IS 'active, archived, deleted';

COMMENT ON COLUMN "conversations"."is_active" IS 'Whether this conversation is currently active for the user';

COMMENT ON COLUMN "conversations"."last_message_at" IS 'Updated with each new message';

COMMENT ON COLUMN "conversations"."last_accessed_at" IS 'Updated when user accesses the conversation';

COMMENT ON COLUMN "conversations"."message_count" IS 'Total messages in conversation';

COMMENT ON COLUMN "messages"."role" IS 'user, assistant, system, tool';

COMMENT ON COLUMN "messages"."metadata" IS 'Additional data: tokens, tool calls, timing';

COMMENT ON COLUMN "message_feedback"."message_id" IS 'The assistant message being rated';

COMMENT ON COLUMN "message_feedback"."is_positive" IS 'true = good, false = not good';

COMMENT ON COLUMN "message_feedback"."is_reviewed" IS 'Whether admin has reviewed this feedback';

COMMENT ON COLUMN "message_feedback"."note" IS 'Optional comment about the feedback';

ALTER TABLE "user_groups" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "user_groups" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE CASCADE;

ALTER TABLE "user_groups" ADD FOREIGN KEY ("added_by") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "chatbots" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "group_chatbots" ADD FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE CASCADE;

ALTER TABLE "group_chatbots" ADD FOREIGN KEY ("chatbot_id") REFERENCES "chatbots" ("id") ON DELETE CASCADE;

ALTER TABLE "group_chatbots" ADD FOREIGN KEY ("assigned_by") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "user_chatbots" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;

ALTER TABLE "user_chatbots" ADD FOREIGN KEY ("chatbot_id") REFERENCES "chatbots" ("id") ON DELETE CASCADE;

ALTER TABLE "user_chatbots" ADD FOREIGN KEY ("assigned_by") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "chatbot_tools" ADD FOREIGN KEY ("chatbot_id") REFERENCES "chatbots" ("id") ON DELETE CASCADE;

ALTER TABLE "chatbot_tools" ADD FOREIGN KEY ("tool_id") REFERENCES "tools" ("id") ON DELETE CASCADE;

ALTER TABLE "conversations" ADD FOREIGN KEY ("chatbot_id") REFERENCES "chatbots" ("id") ON DELETE SET NULL;

ALTER TABLE "conversations" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "messages" ADD FOREIGN KEY ("conversation_id") REFERENCES "conversations" ("id") ON DELETE CASCADE;

ALTER TABLE "message_feedback" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id") ON DELETE CASCADE;

ALTER TABLE "message_feedback" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
