"""Create tables

Revision ID: 29c55130f553
Revises: b120d6fb54ab
Create Date: 2025-11-09 12:05:39.822047+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "29c55130f553"
down_revision = "b120d6fb54ab"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_groups")
    op.drop_table("chatbot_tools")
    op.drop_index("idx_documents_domain", table_name="documents")
    op.drop_index("idx_documents_knowledge_base_id", table_name="documents")
    op.drop_index("idx_documents_upload_status", table_name="documents")
    op.drop_index("idx_documents_uploaded_at", table_name="documents")
    op.drop_index("idx_documents_user_id", table_name="documents")
    op.drop_table("documents")
    op.drop_table("message_feedback")
    op.drop_table("tools")
    op.drop_table("chatbots")
    op.drop_index("idx_messages_conversation_id", table_name="messages")
    op.drop_table("messages")
    op.drop_table("conversations")
    op.drop_table("groups")
    op.drop_table("users")
    op.drop_table("group_chatbots")
    op.drop_table("user_chatbots")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_chatbots",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chatbot_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "assigned_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Admin who assigned this chatbot to the user",
        ),
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
            comment="active, revoked",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name="user_chatbots_assigned_by_fkey",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["chatbot_id"],
            ["chatbots.id"],
            name="user_chatbots_chatbot_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_chatbots_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "chatbot_id", name="user_chatbots_pkey"),
    )
    op.create_table(
        "group_chatbots",
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("chatbot_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "assigned_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Admin who assigned this chatbot to the group",
        ),
        sa.Column(
            "assigned_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
            comment="active, revoked",
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
            name="group_chatbots_assigned_by_fkey",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["chatbot_id"],
            ["chatbots.id"],
            name="group_chatbots_chatbot_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="group_chatbots_group_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "chatbot_id", name="group_chatbots_pkey"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('users_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "is_admin",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
            comment="Admin can create users, chatbots, and groups",
        ),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
            comment="Encrypted password (bcrypt)",
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
            comment="active, disabled, suspended",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint("email", name="users_email_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "groups",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('groups_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name="groups_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "conversations",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('conversations_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("chatbot_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "title",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
            comment="Conversation title, auto-generated or user-defined",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
            comment="active, archived, deleted",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
            comment="Whether this conversation is currently active for the user",
        ),
        sa.Column(
            "started_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_message_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Updated with each new message",
        ),
        sa.Column(
            "last_accessed_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
            comment="Updated when user accesses the conversation",
        ),
        sa.Column(
            "message_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
            comment="Total messages in conversation",
        ),
        sa.ForeignKeyConstraint(
            ["chatbot_id"],
            ["chatbots.id"],
            name="conversations_chatbot_id_fkey",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="conversations_user_id_fkey", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="conversations_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "messages",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('messages_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("conversation_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            sa.VARCHAR(length=20),
            autoincrement=False,
            nullable=False,
            comment="user, assistant, system, tool",
        ),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
            comment="Additional data: tokens, tool calls, timing",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name="messages_conversation_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="messages_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("idx_messages_conversation_id", "messages", ["conversation_id"], unique=False)
    op.create_table(
        "chatbots",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('chatbots_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "provider",
            sa.VARCHAR(length=50),
            autoincrement=False,
            nullable=False,
            comment="openai, anthropic, google",
        ),
        sa.Column(
            "model",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="gpt-4o, claude-3-5-sonnet, gemini-pro",
        ),
        sa.Column(
            "temperature",
            sa.NUMERIC(precision=3, scale=2),
            server_default=sa.text("0.7"),
            autoincrement=False,
            nullable=True,
            comment="0.0-2.0, controls randomness",
        ),
        sa.Column(
            "max_tokens",
            sa.INTEGER(),
            server_default=sa.text("2048"),
            autoincrement=False,
            nullable=True,
            comment="Maximum response length",
        ),
        sa.Column(
            "top_p",
            sa.NUMERIC(precision=3, scale=2),
            server_default=sa.text("1.0"),
            autoincrement=False,
            nullable=True,
            comment="0.0-1.0, nucleus sampling",
        ),
        sa.Column(
            "system_prompt",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Instructions defining bot personality and behavior",
        ),
        sa.Column(
            "welcome_message",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="First message sent to users",
        ),
        sa.Column(
            "fallback_message",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Response when API fails",
        ),
        sa.Column(
            "max_conversation_length",
            sa.INTEGER(),
            server_default=sa.text("50"),
            autoincrement=False,
            nullable=True,
            comment="Messages to remember in context",
        ),
        sa.Column(
            "enable_function_calling",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
            comment="Allow AI to use available tools",
        ),
        sa.Column(
            "api_key_encrypted",
            sa.TEXT(),
            autoincrement=False,
            nullable=False,
            comment="Encrypted API credentials",
        ),
        sa.Column(
            "api_base_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
            comment="Custom API endpoint for Azure/custom deployments",
        ),
        sa.Column(
            "created_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Admin who created this chatbot",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
            comment="active, disabled, archived",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="chatbots_created_by_fkey", ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name="chatbots_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "tools",
        sa.Column(
            "id",
            sa.INTEGER(),
            server_default=sa.text("nextval('tools_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.VARCHAR(length=100),
            autoincrement=False,
            nullable=False,
            comment="Hard-coded tool identifier",
        ),
        sa.Column(
            "description",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Description of what this tool does",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=True,
            comment="active, disabled",
        ),
        sa.PrimaryKeyConstraint("id", name="tools_pkey"),
        sa.UniqueConstraint("name", name="tools_name_key"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "message_feedback",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "message_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="The assistant message being rated",
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "is_positive",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="true = good, false = not good",
        ),
        sa.Column(
            "is_reviewed",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=True,
            comment="Whether admin has reviewed this feedback",
        ),
        sa.Column(
            "note",
            sa.TEXT(),
            autoincrement=False,
            nullable=True,
            comment="Optional comment about the feedback",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name="message_feedback_message_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="message_feedback_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="message_feedback_pkey"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("s3_key", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("domain", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("upload_status", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("processing_status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("uploaded_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("processed_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        sa.Column("knowledge_base_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="documents_pkey"),
    )
    op.create_index("idx_documents_user_id", "documents", ["user_id"], unique=False)
    op.create_index("idx_documents_uploaded_at", "documents", ["uploaded_at"], unique=False)
    op.create_index("idx_documents_upload_status", "documents", ["upload_status"], unique=False)
    op.create_index(
        "idx_documents_knowledge_base_id", "documents", ["knowledge_base_id"], unique=False
    )
    op.create_index("idx_documents_domain", "documents", ["domain"], unique=False)
    op.create_table(
        "chatbot_tools",
        sa.Column("chatbot_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tool_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "added_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["chatbot_id"],
            ["chatbots.id"],
            name="chatbot_tools_chatbot_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"], ["tools.id"], name="chatbot_tools_tool_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("chatbot_id", "tool_id", name="chatbot_tools_pkey"),
    )
    op.create_table(
        "user_groups",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("group_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "added_by",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Admin who added this user to the group",
        ),
        sa.Column(
            "joined_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["added_by"], ["users.id"], name="user_groups_added_by_fkey", ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name="user_groups_group_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_groups_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id", name="user_groups_pkey"),
    )
    # ### end Alembic commands ###
